import type { NextPage } from 'next';
import Head from 'next/head';

import { Text } from 'components/Text/Text';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Nextjs boilerplate</h1>
        <Text />
      </main>
    </div>
  );
};

export default Home;
